import { Order } from '../../types/types';

const ConstantOrders: Array<Order> = [
    {
        id: 1234,
        orderAddress: '서울특별시 관악구 뭐시래기',
        orderAddressDetail: '111번지',
        createdAt: '2022-03-27',
        orderEmail: 'JohnDoe@gmail.com',
        orderCustomerName: 'Doe',
        orderItems: [
            {
                id: 1,
                quantity: 10,
                amount: 1000,
                perfume: {
                    id: 11,
                    perfumer: 'Greatest Perfumer',
                    perfumeTitle: 'Shit Smell',
                    price: 100,
                    country: 'South Korea',
                    description: 'JonNa JoEum',
                    year: 2000,
                    type: 'EDT',
                    volume: '120ml',
                    perfumeGender: 'male',
                    fragranceBaseNotes: '',
                    fragranceMiddleNotes: '',
                    fragranceTopNotes: '',
                    filename: '',
                    file: null,
                    perfumeRating: 5,
                    reviews: [],
                },
            },
            {
                id: 2,
                quantity: 10,
                amount: 1000,
                perfume: {
                    id: 22,
                    perfumer: 'Greatest Perfumer',
                    perfumeTitle: 'Shit Smell',
                    price: 100,
                    country: 'South Korea',
                    description: 'JonNa JoEum',
                    year: 2000,
                    type: 'EDT',
                    volume: '120ml',
                    perfumeGender: 'male',
                    fragranceBaseNotes: '',
                    fragranceMiddleNotes: '',
                    fragranceTopNotes: '',
                    filename: '',
                    file: null,
                    perfumeRating: 5,
                    reviews: [],
                },
            },
            {
                id: 2,
                quantity: 10,
                amount: 1000,
                perfume: {
                    id: 33,
                    perfumer: 'Greatest Perfumer',
                    perfumeTitle: 'Shit Smell',
                    price: 100,
                    country: 'South Korea',
                    description: 'JonNa JoEum',
                    year: 2000,
                    type: 'EDT',
                    volume: '120ml',
                    perfumeGender: 'male',
                    fragranceBaseNotes: '',
                    fragranceMiddleNotes: '',
                    fragranceTopNotes: '',
                    filename: '',
                    file: null,
                    perfumeRating: 5,
                    reviews: [],
                },
            },
        ],
        orderPhoneNumber: '010-1234-5678',
        orderPostIndex: 90876,
        orderTotalPrice: 2000,
    },
];

export default ConstantOrders;
