version: "3"
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: myweb-proxy
    depends_on:
      - web
      - api
  web:
    build: ./
    ports:
      - 3000:3000
    container_name: myweb-web
  api:
    image: devops7503/server_v1.0:latest
    ports:
      - 8080:8080
      - 465:465
      - 587:587
    container_name: myweb-api
