version: "3"
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: iljo-proxy
    depends_on:
      - web
      - api
  web:
    image: devops7503/iljo-web:latest
    ports:
      - 3000:3000
    container_name: iljo-web
  api:
    image: devops7503/iljo-api:latest
    ports:
      - 8080:8080
    container_name: iljo-api
